### ISSUE TITLE
大神你好，请教个问题

### ISSUE THREAD

**Issue by qingchen1016** [yewei02538/TodayNews#5]
顶部导航栏滑动过度时的那个样式真心赞，可我看了半天没理解是什么原理，我想把这块改成那种普通的底部是一条横线的过度方式，请问大概在哪块修改呢？

**Comment by yewei02538** [comment]
你更新下，主要是更改mTranslationX移动画布然后drawLine,ColorTrackTabViewIndicator里面有个mIndicatorColor，你可以在布局里面直接使用app:ctTabIndicatorColor="@color/red"

**Comment by qingchen1016** [comment]
好的  我试试先，非常感谢哈

**Comment by qingchen1016** [comment]
你好，加上ctTabIndicatorColor这条属性之后，底部横线就出现了，但是有个问题是滑动选项卡时横线不跟着上方变色的字体块一起移动，横线移动的距离比较短，请教下这是怎么回事呢

**Comment by yewei02538** [comment]
那个计算有点问题，我提交了代码，你更新下就可以了

**Comment by qingchen1016** [comment]
更新以后滑动没毛病了，妥妥的，可是点击tab的时候横线还是没有跟上  233333333

**Comment by yewei02538** [comment]
哈哈 ，不好意思啊，这几天比较忙，忘记测试了。。233333,  已提交，更新下就好了。这个类没写好，我得抽个时间重新写下

**Comment by qingchen1016** [comment]
已经很厉害了大神

**Comment by qingchen1016** [comment]
我找了半天，愣是没找到首页上方viewpager里面的新闻列表加载的具体实现的类，只感觉NewsListFragment比较像，但是却又没找到下拉刷新或者是加载该页的网络请求等功能的具体位置，难道这就是MVP模式的神秘之处？以前开发一直用的是类似mvc模式的开发方式，时间一长，单个ancticity的极臃肿，甚至能达到4.5千行。

**Comment by qingchen1016** [comment]
主要是没看明白数据List<News> 从哪里来的，这块数据的网络请求没找到...

**Comment by yewei02538** [comment]
数据请求、逻辑都在`Presenter`层，`NewsListFragment`里调用了`mvpPresenter.getNewsList(mTitleCode);`然后在`NewsListPresenter`里面进行数据请求，请求成功后返回给`view`层，`view`是个接口，`activity`是它的具体实现类，数据返回后在做相应的操作。使用mvp可以使得逻辑非常的清晰，非常的丝滑

**Comment by qingchen1016** [comment]
已经捋清楚啦，正在学习Retrofit中，有没有荣幸加QQ和大神交流下

**Comment by yewei02538** [comment]
恩恩，你qq多少，我加你

**Comment by qingchen1016** [comment]
787485820     我看到你的这qq我实在破译不了  2333   是md5还是啥的生成的吗      QQ:90CF77BADBDF712D1CA6B6A7F444B9F6

**Comment by JanusKun** [comment]
网络不行吗？我一直在Building,有点气

**Comment by yewei02538** [comment]
是一直building gradle project info吗？网上有解决办法，修改下gradle-wrapper.properties文件下distributionUrl一行，改成你的项目中的gradle-wrapper.properties。

**Comment by newtonnl** [comment]
大神真厉害，这个内容是通过今日头条网站获取的么 这个app能不能理解为主要为应用前端呢

**Comment by yewei02538** [comment]
是今日头条网站抓包获取的呢。差不多吧，后期会添加其他功能
